
[project]
name = "awesome-ogd-switzerland"
version = "0.1.0"
description = "Link checker for awesome-ogd-switzerland"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "rich>=14.2.0"
]

